name: Build docker image

on:
  push:
    branches:
      - 'main'
    paths:
      - Dockerfile
      - entrypoint.sh
  pull_request:
    branches:
      - '*'
    paths:
      - Dockerfile
      - entrypoint.sh

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: false
          tags: maxime1907/srcds:latest
